# webforms.ex 2.1 - The Back-End Part of WebForms Core Technology, Owned by Elanat (https://elanat.net)
# Compatible with WebFormsJS version 2.1

defmodule WebFormsCore.HtmlEventListener do
  def abort, do: "abort"
  def after_print, do: "afterprint"
  def before_print, do: "beforeprint"
  def before_unload, do: "beforeunload"
  def blur, do: "blur"
  def can_play, do: "canplay"
  def can_play_through, do: "canplaythrough"
  def change, do: "change"
  def click, do: "click"
  def copy, do: "copy"
  def cut, do: "cut"
  def double_click, do: "dblclick"
  def drag, do: "drag"
  def drag_end, do: "dragend"
  def drag_enter, do: "dragenter"
  def drag_leave, do: "dragleave"
  def drag_over, do: "dragover"
  def drag_start, do: "dragstart"
  def drop, do: "drop"
  def duration_change, do: "durationchange"
  def ended, do: "ended"
  def error, do: "error"
  def focus, do: "focus"
  def focusin, do: "focusin"
  def focus_out, do: "focusout"
  def hash_change, do: "hashchange"
  def input, do: "input"
  def invalid, do: "invalid"
  def key_down, do: "keydown"
  def key_press, do: "keypress"
  def key_up, do: "keyup"
  def load, do: "load"
  def loaded_data, do: "loadeddata"
  def loaded_meta_data, do: "loadedmetadata"
  def load_start, do: "loadstart"
  def mouse_down, do: "mousedown"
  def mouse_enter, do: "mouseenter"
  def mouse_leave, do: "mouseleave"
  def mouse_move, do: "mousemove"
  def mouse_over, do: "mouseover"
  def mouse_out, do: "mouseout"
  def mouse_up, do: "mouseup"
  def offline, do: "offline"
  def online, do: "online"
  def page_hide, do: "pagehide"
  def page_show, do: "pageshow"
  def paste, do: "paste"
  def pause, do: "pause"
  def play, do: "play"
  def playing, do: "playing"
  def progress, do: "progress"
  def rate_change, do: "ratechange"
  def resize, do: "resize"
  def reset, do: "reset"
  def scroll, do: "scroll"
  def search, do: "search"
  def seeked, do: "seeked"
  def seeking, do: "seeking"
  def select, do: "select"
  def stalled, do: "stalled"
  def submit, do: "submit"
  def suspend, do: "suspend"
  def time_update, do: "timeupdate"
  def toggle, do: "toggle"
  def touch_cancel, do: "touchcancel"
  def touchend, do: "touchend"
  def touch_move, do: "touchmove"
  def touch_start, do: "touchstart"
  def unload, do: "unload"
  def volume_change, do: "volumechange"
  def waiting, do: "waiting"
  def wheel, do: "wheel"

  def animation_end, do: "animationend"
  def animation_iteration, do: "animationiteration"
  def animation_start, do: "animationstart"
  def context_menu, do: "contextmenu"
  def full_screen_change, do: "fullscreenchange"
  def full_screen_error, do: "fullscreenerror"
  def pop_state, do: "popstate"
  def transition_end, do: "transitionend"
  def storage, do: "storage"

  # Custom
  def scroll_bottom, do: "scrollbottom" # Need Call EnableScrollBottomEvent Method Before
  def element_reached, do: "elementreached" # Need Call EnableReachedElementEvent Method Before
end